### ISSUE TITLE
[course-intro] css issue when using the slots provided

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1120]
@cgldevel reported this issue after moving to 6.0.1

manually applying this CSS showed it works. Let's see...

```css
course-intro-footer {
   display: flex;
    justify-content: space-between;
    background: #000;
    padding: 25px;
    min-height: 300px;
    align-items: center;
}
```

Let's also add "part" while we're at it so we can dig into it deeper in the future if needed.
