### ISSUE TITLE
flash-card slightly offset once saved without columns

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1482]

**Comment by btopro** [comment]
This is related to this line of css in clean-one:
```css
.main-content *, .main-content ::slotted(*) {
box-sizing: border-box;
}
```

Never had an issue w/ this sorta thing before but flash-card now sets it's box
