### ISSUE TITLE
[hax-body] Proposal to remove base.css and hax-body styling

### ISSUE THREAD

**Issue by heyMP** [elmsln/issues#189]
To improve the developer UX I'm proposing that we eliminate any default styling to the hax-body content area.  The issue is that developers have to explicitly set each of the css variables that are you present in the hax-body styles.  This creates a small but still confusing step right off the bat when working with HAX.

Alternatively, what could inject user specified css files into hax-body.  That would ensure the styling in the lightdom would near 100% match the styling in the hax-body shadow dom.

In our hax11ty project, there is a proof of concept where we inject styles into the h-a-x tag.

```
  connectedCallback() {
    super.connectedCallback();
    this.__applyMO();
    window.addEventListener("hax-store-ready", this.injectHaxStyles.bind(this));
  }
  /**
   * Inject core styles
   */
  injectHaxStyles() {
    const styleTag = document.createElement('style');
    const hax = this.shadowRoot.querySelector('h-a-x').shadowRoot;
    fetch('/assets/css/styles.css')
      .then(res => res.text())
      .then(res => {
        styleTag.innerText = res;
        hax.appendChild(styleTag);
      })
  }
```
https://github.com/elmsln/hax11ty/blob/master/assets/js/components/eleventy-hax.js

## Possible Usage

We could add a property to the appstore spec or connection settings that contains an array of `user-css` files.  That setting is loaded into the store and available for hax-body to make a fetch call to those css files and inject them into its shadow root.

## Trade offs

Trades off is that there is an extra step in loading the css files and injecting them.  This results in a flash of unstyled content.  The good thing is that those css files would almost certainly have to requested on initial page load so they would be cached.

The good news is that this would only occur for users who have editing rights.

**Comment by btopro** [comment]
so if we drop the default do we need to have another one?

**Comment by btopro** [comment]
base.css? Do you mean the styles in `h-a-x` like `h1` and what not? I don't care for the injecting concept but we could always allow for that as a fallback. `hax-body` has styles as well so I assume you mean `:host #bodycontainer ::slotted(` type selectors yes? I'm ok with removing these if it makes the DX better though we will need some of them to maybe only apply to an editable state. For example paragraphs that are empty need a min heigth and lists padding around them so you can drop above them, etc.

**Comment by heyMP** [comment]
the styles in hax-body.  I was working on a prototype and this is what I was removing:

```
        :host #bodycontainer ::slotted(h1) {
          font-size: var(--hax-base-styles-h1-font-size, 2.5em);
          line-height: var(--hax-base-styles-h1-line-height, 2.5em);
        }
        :host #bodycontainer ::slotted(h2) {
          font-size: var(--hax-base-styles-h2-font-size, 2em);
        }
        :host #bodycontainer ::slotted(h3) {
          font-size: var(--hax-base-styles-h3-font-size, 1.75em);
        }
        :host #bodycontainer ::slotted(h4) {
          font-size: var(--hax-base-styles-h4-font-size, 1.5em);
        }
        :host #bodycontainer ::slotted(h5) {
          font-size: var(--hax-base-styles-h5-font-size, 1.25em);
        }
        :host #bodycontainer ::slotted(h6) {
          font-size: var(--hax-base-styles-h6-font-size, 1.25em);
        }
        :host #bodycontainer ::slotted(p) {
          min-height: var(--hax-base-styles-p-min-height, 43px);
          font-size: var(--hax-base-styles-p-font-size, 24px);
          line-height: var(--hax-base-styles-p-line-height, 1.8);
          letter-spacing: var(--hax-base-styles-p-letter-spacing, 0.5px);
        }
        :host #bodycontainer ::slotted(a) {
          color: var(
            --hax-base-styles-a-color,
            var(--simple-colors-default-theme-grey-12, #000)
          );
          font-size: var(--hax-base-styles-a-font-size, 24px);
          font-weight: var(--hax-base-styles-a-font-weight, normal);
        }
        :host #bodycontainer ::slotted(a:visited) {
          color: var(
            --hax-base-styles-a-color-visited,
            var(--simple-colors-default-theme-light-blue, #007ffc)
          );
        }
        :host #bodycontainer ::slotted(a:active),
        :host #bodycontainer ::slotted(a:focus),
        :host #bodycontainer ::slotted(a:hover) {
          color: var(
            --hax-base-styles-a-color-active,
            var(--simple-colors-default-theme-light-blue, #007ffc)
          );
          font-weight: var(--hax-base-styles-a-font-weight-active, normal);
        }
        :host #bodycontainer ::slotted(ol),
        :host #bodycontainer ::slotted(ul),
        :host #bodycontainer ::slotted(li) {
          padding-bottom: var(--hax-base-styles-list-padding-bottom, 1.5em);
          line-height: var(--hax-base-styles-list-line-height, 40px);
          font-size: var(--hax-base-styles-list-font-size, 24px);
          max-width: var(--hax-base-styles-list-max-width, 28em);
        }
        :host #bodycontainer ::slotted(ol > li:last-child),
        :host #bodycontainer ::slotted(ul > li:last-child) {
          padding-bottom: var(
            --hax-base-styles-list-last-child-padding-bottom,
            1em
          );
        }
        :host #bodycontainer ::slotted(ul),
        :host #bodycontainer ::slotted(ol) {
          padding-left: var(--hax-base-styles-list-padding-left, 20px);
          padding-left: var(--hax-base-styles-list-margin-left, 20px);
        }

```

Keep the ones that directly influence the editor. 

For the empty div's, maybe we could replace it with the `:empty` selector

https://css-tricks.com/almanac/selectors/e/empty/

**Comment by btopro** [comment]
alright, just issue a PR with what fixes your issue and then we'll reverse patch stuff downstream as needed. If it's not in `[edit-mode]` then it shouldn't matter. We may want to take the things abstracted and put them in a base.css of some kind (though they might already be in the base.css that haxcms leverages). Either way your right this shouldn't make assumptions about how to present stuff in the body area.

**Comment by btopro** [comment]
@heyMP I'm going to add a `:host([edit-mode])` selector to all these styles. They are important for the most part so that when editing you have enough spacing to drop between the `<p>` tags or `<ul>`s to be editable. If we get complaints about this looking slightly different when switching out of edit mode we can slowly remove these from there. seem reasonable?

**Comment by btopro** [comment]
Feel free to gut base.css my only concern is the actual editor in edit mode

**Comment by btopro** [comment]
Ok, I think I found a solution for this. We remove ALL style implication, while leaving behind empty css vars that can still be used to get at these things in the shadows.

So... now 0 css implication in hax, however, these will influence the body of content in these specific areas:
```css
      html {
        font-family: 'Noto Serif', serif;
        --haxcms-base-styles-body-font-size: 16px;
        --haxcms-base-styles-body-font-family: 'Noto Serif', serif;
        --haxcms-base-styles-body-line-height: 1.8;
        --haxcms-base-styles-body-letter-spacing: .5px;
        --hax-base-styles-h1-font-size: 2.5em;
        --hax-base-styles-h1-line-height: 2.5em;
        --hax-base-styles-h2-font-size: 2em;
        --hax-base-styles-h3-font-size: 1.75em;
        --hax-base-styles-h4-font-size: 1.5em;
        --hax-base-styles-h5-font-size: 1.25em;  
        --hax-base-styles-h6-font-size: 1.25em;
        --hax-base-styles-p-min-height: 43px;
        --hax-base-styles-p-font-size: 24px;
        --hax-base-styles-p-line-height: 1.8;
        --hax-base-styles-p-letter-spacing: .5px;
        --hax-base-styles-a-color: #2196f3;
        --hax-base-styles-a-font-size: 24px;
        --hax-base-styles-a-font-weight: normal;
        --hax-base-styles-a-color-visited: #2196f3;
        --hax-base-styles-a-color-active: #2196f3;
        --hax-base-styles-a-font-weight-active: normal;
        --hax-base-styles-list-line-height: 1.8;
        --hax-base-styles-list-font-size: 24px;
        --hax-base-styles-list-max-width: 28em;
        --hax-base-styles-list-padding-left: 1em;
        --hax-base-styles-list-margin-left: 1em;
      }
```
