### ISSUE TITLE
make a way for existing themes to usurp DDD

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1901]
Need to go into the themes and effectively highjack these values away from DDD (for the time being...) so that they conform to what they have been. Then, we'll implement DDD across all designs and we'll ax it out of there at that time but then we can say that its "an official university brand and styling effort"

```css
          body,
          html,
          :root,
          :host {
            /* global override font styles for light-dom content */
            --ddd-theme-body-font-size: var(--ddd-font-size-xxs);
            --ddd-theme-h1-font-size: var(--ddd-font-size-l);
            --ddd-theme-h2-font-size: var(--ddd-font-size-m);
            --ddd-theme-h3-font-size: var(--ddd-font-size-ms);
            --ddd-theme-h4-font-size: var(--ddd-font-size-s);
            --ddd-theme-h5-font-size: var(--ddd-font-size-xs);
            --ddd-theme-h6-font-size: var(--ddd-font-size-xxs);
}
```
