### ISSUE TITLE
[music-player] add an additional visual that's piano only

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#373]
```css
.waterfall-notes-container {
    display: none;
}
```
We should be able to hide the container in the visualization element and select the same setting but then just hide part of it
